"""
face_anim.py — Surprise face animation player.

Loads pre-rendered eye/mouth numpy clips (generated by render_eye_frames.py
and render_mouth_frames.py) and fires them at random intervals while the app
is in CLOCK state.

Integration:
    - Call load() once (blocking, runs at startup).
    - Call start() after displays are ready.
    - Call set_active(True)  when entering CLOCK state.
    - Call set_active(False) when leaving  CLOCK state.
    - Check is_playing before submitting to displays in the main loop.
    - Call stop() on shutdown.
"""
from __future__ import annotations

import os
import random
import threading
import time
from typing import TYPE_CHECKING

import numpy as np
from PIL import Image

if TYPE_CHECKING:
    from display.manager import DisplayManager

# ── Paths ─────────────────────────────────────────────────────────────────────
_ANIM_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "animations")

# ── Clip catalogue ────────────────────────────────────────────────────────────
# (name, weight) — higher weight = fired more often
_EYE_CATALOGUE = [
    ("blink_fast",       0.26),
    ("blink_slow",       0.16),
    ("double_blink",     0.14),
    ("saccade_left",     0.10),
    ("saccade_right",    0.10),
    ("saccade_up",       0.08),
    ("saccade_diagonal", 0.08),
    ("suspicious",       0.05),
    ("sleepy",           0.03),
]
_MOUTH_CATALOGUE = [
    ("smile",    0.32),
    ("smirk",    0.24),
    ("surprise", 0.20),
    ("yawn",     0.14),
    ("grimace",  0.10),
]

# Probability that only eye fires (vs both together)
_PROB_EYE_ONLY = 0.15

# ── Timing ────────────────────────────────────────────────────────────────────
_EYE_FPS   =  9
_MOUTH_FPS = 10
# Random wait between animations: non-uniform distribution for organic feel.
# Most waits cluster around 30–60 s; occasional short (15 s) or long (90 s) gaps.
_WAIT_MIN  = 15.0
_WAIT_MAX  = 90.0
_WAIT_MODE = 40.0   # triangular distribution peak


class FaceAnimator:
    """Random surprise face animator for both clock displays."""

    def __init__(self, displays: DisplayManager) -> None:
        self._displays = displays

        self._eye_clips:   dict[str, np.ndarray] = {}
        self._mouth_clips: dict[str, np.ndarray] = {}

        self._active  = False
        self._playing = False          # True while a clip is being rendered
        self._lock    = threading.Lock()
        self._stop_ev = threading.Event()
        self._thread: threading.Thread | None = None

    # ── Public API ────────────────────────────────────────────────────────────

    def load(self) -> None:
        """Load all .npy clip files into RAM.  Call ONCE at startup (blocking)."""
        for name, _ in _EYE_CATALOGUE:
            path = os.path.join(_ANIM_DIR, f"eye_{name}.npy")
            if os.path.exists(path):
                self._eye_clips[name] = np.load(path)
                print(f"[Face] eye_{name}: {self._eye_clips[name].shape[0]} frames")
            else:
                print(f"[Face] MISSING {path}  →  run render_eye_frames.py first")

        for name, _ in _MOUTH_CATALOGUE:
            path = os.path.join(_ANIM_DIR, f"mouth_{name}.npy")
            if os.path.exists(path):
                self._mouth_clips[name] = np.load(path)
                print(f"[Face] mouth_{name}: {self._mouth_clips[name].shape[0]} frames")
            else:
                print(f"[Face] MISSING {path}  →  run render_mouth_frames.py first")

    def start(self) -> None:
        """Spawn the background timer thread.  Call after displays are ready."""
        if not self._eye_clips and not self._mouth_clips:
            print("[Face] no clips loaded — animator disabled")
            return
        self._stop_ev.clear()
        self._thread = threading.Thread(
            target=self._loop, daemon=True, name="FaceAnimator"
        )
        self._thread.start()
        print("[Face] animator started")

    def stop(self) -> None:
        """Signal the animator to stop (non-blocking)."""
        self._stop_ev.set()

    def set_active(self, active: bool) -> None:
        """Enable or disable random firing.  Pass True in CLOCK state only."""
        self._active = active

    @property
    def is_playing(self) -> bool:
        """True while an animation clip is being rendered to a display.
        The main render loop should skip display submission when True."""
        return self._playing

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _wait_interval(self) -> float:
        """Triangular-distributed wait — feels more random than uniform."""
        return random.triangular(_WAIT_MIN, _WAIT_MAX, _WAIT_MODE)

    def _loop(self) -> None:
        while not self._stop_ev.is_set():
            wait = self._wait_interval()
            deadline = time.monotonic() + wait
            while time.monotonic() < deadline:
                if self._stop_ev.is_set():
                    return
                time.sleep(0.5)
            if self._active and not self._playing:
                self._fire()

    def _fire(self) -> None:
        with self._lock:
            if self._playing:
                return
            self._playing = True
        try:
            self._play_combo()
        finally:
            with self._lock:
                self._playing = False

    # ── Combo logic ───────────────────────────────────────────────────────────

    def _pick_eye(self) -> tuple[str, np.ndarray] | None:
        names  = [n for n, _ in _EYE_CATALOGUE if n in self._eye_clips]
        if not names:
            return None
        weights = [w for n, w in _EYE_CATALOGUE if n in self._eye_clips]
        name   = random.choices(names, weights=weights, k=1)[0]
        return name, self._eye_clips[name]

    def _pick_mouth(self) -> tuple[str, np.ndarray] | None:
        names  = [n for n, _ in _MOUTH_CATALOGUE if n in self._mouth_clips]
        if not names:
            return None
        weights = [w for n, w in _MOUTH_CATALOGUE if n in self._mouth_clips]
        name   = random.choices(names, weights=weights, k=1)[0]
        return name, self._mouth_clips[name]

    def _play_combo(self) -> None:
        eye_pick   = self._pick_eye()
        mouth_pick = self._pick_mouth()

        if not eye_pick:
            return

        e_name, e_frames = eye_pick

        # 85% of the time animate both; 15% eye only (subtle blinks)
        if mouth_pick and random.random() > _PROB_EYE_ONLY:
            m_name, m_frames = mouth_pick
            print(f"[Face] -> eye_{e_name} + mouth_{m_name}")
            eye_t = threading.Thread(
                target=self._play_eye, args=(e_frames,), daemon=True
            )
            eye_t.start()
            self._play_mouth(m_frames)
            eye_t.join()
        else:
            print(f"[Face] -> eye_{e_name}")
            self._play_eye(e_frames)

    # ── Playback ──────────────────────────────────────────────────────────────

    def _play_eye(self, frames: np.ndarray) -> None:
        delay = 1.0 / _EYE_FPS
        for f in frames:
            if not self._active or self._stop_ev.is_set():
                break
            if self._displays.round:
                self._displays.round.render(Image.fromarray(f))
            time.sleep(delay)

    def _play_mouth(self, frames: np.ndarray) -> None:
        delay = 1.0 / _MOUTH_FPS
        for f in frames:
            if not self._active or self._stop_ev.is_set():
                break
            if self._displays.rect:
                self._displays.rect.render(Image.fromarray(f))
            time.sleep(delay)
